In [31]:
import numpy as np

In [32]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
for e in arr:
    print(e)

[0 1 2]
[3 4 5]
[6 7 8]


In [34]:
for i in np.nditer(arr):
    print(i)

0
1
2
3
4
5
6
7
8


In [35]:
np.ravel(arr) #

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
arr1 = np.array([[1,2,3,4], [5,6,7,8]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
arr2=np.array([[11,12,13,14],[15,16,17,18]])
arr2

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [38]:
np.hstack([arr1,arr2])  #rows adds of both array

array([[ 1,  2,  3,  4, 11, 12, 13, 14],
       [ 5,  6,  7,  8, 15, 16, 17, 18]])

In [39]:
np.vstack([arr1,arr2])  #arr add after another

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [11, 12, 13, 14],
       [15, 16, 17, 18]])

In [40]:
np.repeat(arr,2)  #each element by given time

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8])

In [41]:
arr= np.array([2,3])
arr

array([2, 3])

In [42]:
np.repeat(arr, (1,2))  #each index element by given time

array([2, 3, 3])

In [43]:
arr= np.array([[2,3],[4,5]])
arr

array([[2, 3],
       [4, 5]])

In [44]:
np.repeat(arr,(1,2,2,3))  #each index element by given time

array([2, 3, 3, 4, 4, 5, 5, 5])

In [45]:
arr= np.array([2,3])
arr

array([2, 3])

In [46]:
np.tile(arr, 2)   #add arr duplicate

array([2, 3, 2, 3])

In [47]:
arr=np.insert(arr, 1, 4)  #index,value
arr

array([2, 4, 3])

In [48]:
arr1=np.array([3,4])   
np.concatenate([arr, arr1])  #merge two arr

array([2, 4, 3, 3, 4])