import numpy as np

In [5]:
myarr = np.array([[3,4,5,55]], np.int64)
myarr[0,1]

np.int64(4)

In [6]:
myarr.shape

(1, 4)

In [7]:
myarr.dtype

dtype('int64')

In [8]:
myarr[0,1]=45

In [9]:
myarr

array([[ 3, 45,  5, 55]])

In [10]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [11]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [12]:
listarray.dtype

dtype('int64')

In [13]:
listarray.shape

(3, 3)

In [14]:
listarray.size

9

In [15]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [16]:
zeros = np.zeros((2,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
rng=np.arange(15)

In [21]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
lspace=np.linspace(1,5,12) #Exact partitions

In [24]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [25]:
emp=np.empty((4,6))

In [26]:
emp

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        7.56602523e-307, 7.56587585e-307, 7.56593017e-307],
       [1.60217812e-306, 1.11261095e-306, 1.42417221e-306,
        1.37961641e-306, 2.22522597e-306, 1.33511969e-306],
       [6.23038336e-307, 9.34609790e-307, 8.45593934e-307,
        9.34600963e-307, 1.86921143e-306, 6.23061763e-307],
       [6.23053954e-307, 1.11260416e-306, 1.06811422e-306,
        1.42419530e-306, 2.22522596e-306, 2.22522596e-306]])

In [27]:
emp_like = np.empty_like(lspace)

In [28]:
emp_like

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [31]:
ide = np.identity(45)

In [32]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(45, 45))

In [33]:
ide.shape

(45, 45)

In [34]:
arr = np.arange(99)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [38]:
arr=arr.reshape(3,33)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [39]:
arr=arr.ravel()

In [40]:
arr.shape

(99,)

In [41]:
#Axis
x=[[1,2,3],[4,5,6],[7,1,0]]

In [42]:
ar=np.array(x)

In [43]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [44]:
ar.sum(axis=0)

array([12,  8,  9])

In [45]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [46]:
ar.T #Transpose

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [47]:
ar.flat

In [49]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [50]:
ar.ndim

2

In [51]:
ar.size

9

In [52]:
ar.nbytes #Total bytes consuming by created array

72

In [53]:
one = np.array([1,3,4,634,3])

In [54]:
one.argmax() #Gives index where finds largest value in the array

np.int64(3)

In [55]:
one.argmin() #Gives index where finds lowest value in the array

np.int64(0)

In [56]:
one.argsort() #Returns indexes of values in sorted manner

array([0, 1, 4, 2, 3])

In [57]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [58]:
ar.argmin()

np.int64(8)

In [59]:
ar.argmax()

np.int64(6)

In [60]:
ar.argmax(axis=0)

array([2, 1, 1])

In [61]:
ar.argmax(axis=1)

array([2, 2, 0])

In [62]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [63]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [64]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [66]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [69]:
ar2 = np.array([[1,2,1],
                [4,0,6],
                [8,1,0]])

In [70]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [71]:
[324,34] + [34,546]

[324, 34, 34, 546]

In [72]:
ar 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [73]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [74]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [75]:
np.sqrt(ar) #squareroots

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [76]:
ar.sum()

np.int64(29)

In [77]:
ar.max()

np.int64(7)

In [78]:
ar.min()

np.int64(0)

In [79]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [80]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [81]:
type(np.where(ar>5))

tuple

In [82]:
np.count_nonzero(ar) #Counts nonzeros

np.int64(8)

In [83]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [84]:
ar[1,2]=0

In [85]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [86]:
import sys

In [87]:
py_ar=[0,4,55,2]

In [88]:
np_ar=np.array(py_ar)

In [90]:
sys.getsizeof(1)*len(py_ar)

112

In [91]:
np_ar.itemsize*np_ar.size

32