In [6]:
import numpy as np

#create array using numpy
#create a 1D array

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape) #single-dimension

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [8]:
#1D Array

arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) #rows-1, columns-5

array([[1, 2, 3, 4, 5]])

In [9]:
#2D Array

arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape) #prints the no of rows, no of columns(_,_)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [11]:
np.arange(0,10,2).reshape(5,1) #prints 0-10, by gap of 2 and reshaping as rows-5 and column-1

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.ones((3,4)) 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
#Identity Matrix - Diagonal elements are 1, others are 0

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
#Attributes of NumPy Array

arr=np.array([[1,2,3],[4,5,6]])

print("Array:\n",arr)
print("Shape:\n",arr.shape) #(2,3)
print("Number of Dimensions:\n",arr.ndim) #2
print("Size (Number of Elements):\n",arr.size)
print("Data Type :", arr.dtype) #int64(may vary)
print("Item Size(in bytes) :", arr.itemsize) #8(may vary)

Array:
 [[1 2 3]
 [4 5 6]]
Shape:
 (2, 3)
Number of Dimensions:
 2
Size (Number of Elements):
 6
Data Type : int64
Item Size(in bytes) : 8


In [18]:
#NumPy Vectorized Operation

arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

#Element-wise Addition
print("Addition:",arr1+arr2)

#Element-wise Subtraction
print("Subtraction:",arr1-arr2)

#Element-wise Multiplication
print("Multiplication:",arr1*arr2)

#Element-wise Division
print("Division:",arr1/arr2)


Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [19]:
#Universal Functions

arr=np.array([2,3,4,5,6])

#Squareroot
print(np.sqrt(arr))

#Exponential
print(np.exp(arr))

#Sine
print(np.sin(arr))

#Natural Log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [20]:
#Array Slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array :\n",arr)

Array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
# Accessing Element
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [24]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [26]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [27]:
#Modify Array Elements

arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [28]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [29]:
#Statistical Concepts - Normalization
#(To convert a data in mean of 0 and standard deviation of 1)

data=np.array([1,2,3,4,5])

#Calculate the mean and standard deviation
mean=np.mean(data)
std_dev=np.std(data)

#Normalize the data
normalized_data=(data - mean) / std_dev
print("Normalized data:",normalized_data)




Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [30]:
#Mean, Mode, Median

data = np.array([1,2,3,4,5,6,7,8,9,10])

#Mean
mean=np.mean(data)
print("Mean:",mean)

#Median
median=np.median(data)
print("Median:",median)

#Standard Deviation
std_dev=np.std(data)
print("Standard Deviation:",std_dev)

#Variance
variance=np.var(data)
print("Variance:",variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [33]:
#Logical Operations

data=np.array([1,2,3,4,5,6,7,8,9,10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])