In [1]:
import numpy as np

In [2]:
#Create a 3×3 array of all True Boolean values

arr=np.full(9,True).reshape(3,3)
arr
     

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [3]:
#Extract odd numbers from an array

arr=np.arange(5,17).reshape(3,4)
arr

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [5]:
arr[arr%2==1]

array([ 5,  7,  9, 11, 13, 15])

In [6]:
#Replace all odd numbers with -1

arr[arr%2==1]=-1
arr

array([[-1,  6, -1,  8],
       [-1, 10, -1, 12],
       [-1, 14, -1, 16]])

In [7]:
#Reverse columns of a 2D array

arr=np.arange(5,17).reshape(3,4)
rev=np.flip(arr,axis=1)
rev
     

array([[ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

In [8]:
#Get indices of elements greater than 5 [hint: check where method of numpy]

arr=np.random.randint(1,10,9).reshape(3,3)
arr

array([[9, 2, 3],
       [9, 6, 2],
       [1, 1, 1]], dtype=int32)

In [9]:
row,col=np.where(arr>5)
np.stack((row,col),axis=1)

array([[0, 0],
       [1, 0],
       [1, 1]])

In [10]:
#Access last row - last column

arr

array([[9, 2, 3],
       [9, 6, 2],
       [1, 1, 1]], dtype=int32)

In [11]:
last=arr[-1,-1]
last

np.int32(1)

In [12]:
# Normalize a NumPy array [ to normalize means scaling the values of 
# an array into a specific range, often [0, 1]]

arr
     

array([[9, 2, 3],
       [9, 6, 2],
       [1, 1, 1]], dtype=int32)

In [13]:
min_val = np.min(arr)
max_val = np.max(arr)
normalized_arr = (arr - min_val) / (max_val - min_val)
normalized_arr

array([[1.   , 0.125, 0.25 ],
       [1.   , 0.625, 0.125],
       [0.   , 0.   , 0.   ]])

In [14]:
arr.flatten()

array([9, 2, 3, 9, 6, 2, 1, 1, 1], dtype=int32)

In [16]:
# Create a 5×5 array with 1 on border and 0 inside

arr=np.zeros([3,3])
arr     

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
out = np.pad(arr, pad_width=1, constant_values=1)
out

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
# Create a random array of 10×10: perform stats (min, max, mean, std)

arr1=np.random.random([10,10])
arr1

array([[0.39802182, 0.98285224, 0.1486763 , 0.21449436, 0.01058042,
        0.70217796, 0.83665004, 0.2437781 , 0.19075706, 0.53540079],
       [0.15238463, 0.74981459, 0.29281941, 0.19160556, 0.91893787,
        0.80699344, 0.04001115, 0.24268456, 0.53290521, 0.20812241],
       [0.33093896, 0.41478719, 0.93011693, 0.08900591, 0.18155564,
        0.2030931 , 0.99125118, 0.14844837, 0.30689474, 0.48681217],
       [0.44712381, 0.5266003 , 0.07933298, 0.13147182, 0.25869998,
        0.33275162, 0.06565547, 0.28331894, 0.44427978, 0.63515537],
       [0.66144909, 0.41172601, 0.05116032, 0.24634144, 0.66214894,
        0.17312274, 0.59674344, 0.260656  , 0.18645621, 0.50025448],
       [0.79018586, 0.28751579, 0.6717549 , 0.84235414, 0.19815507,
        0.97188698, 0.84192653, 0.71315096, 0.54718326, 0.19747486],
       [0.48417994, 0.00452991, 0.96230636, 0.90219476, 0.05706125,
        0.98303377, 0.50517028, 0.96543735, 0.10277375, 0.18771155],
       [0.09576564, 0.53593443, 0.3979035

In [19]:
np.min(arr1)

np.float64(0.004529907628127106)

In [20]:
np.max(arr1)

np.float64(0.9912511773242957)

In [21]:
np.mean(arr1)

np.float64(0.45931520861442005)

In [22]:
np.std(arr1)

np.float64(0.2847014902414839)

In [23]:
# Broadcast a 1D array over a 2D array [all possible scenarios]

arr=np.arange(5,17).reshape(3,4)
arr

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [24]:
arr2=np.array([1,3,5,6])
arr2

array([1, 3, 5, 6])

In [25]:
arr+arr2

array([[ 6,  9, 12, 14],
       [10, 13, 16, 18],
       [14, 17, 20, 22]])

In [26]:
arr3=np.array([[4],[5],[6]])
arr3

array([[4],
       [5],
       [6]])

In [27]:
arr+arr3

array([[ 9, 10, 11, 12],
       [14, 15, 16, 17],
       [19, 20, 21, 22]])

In [28]:
# Sort a 2D array by column 1 [hint: check method argsort()]

arr=np.random.randint(10,22,9).reshape(3,3)
arr

array([[11, 20, 18],
       [14, 17, 15],
       [19, 17, 20]], dtype=int32)

In [29]:
sort = arr[arr[:,1].argsort()]
sort

array([[14, 17, 15],
       [19, 17, 20],
       [11, 20, 18]], dtype=int32)

In [30]:
# Find common elements between two arrays [with and without using intersect1d, 
# use isin() instead]

arr1 = np.array([0, 10, 20, 40, 60, 10])
arr2 = np.array([10, 30, 40, 50])
arr1     

array([ 0, 10, 20, 40, 60, 10])

In [31]:
arr2

array([10, 30, 40, 50])

In [32]:
#Intersected

common = np.intersect1d(arr1,arr2)
common

array([10, 40])

In [33]:
mask=np.isin(arr1, arr2)
mask

array([False,  True, False,  True, False,  True])

In [35]:
common=arr1[mask]
unique=np.unique(common)
unique     

array([10, 40])

In [36]:
# Subtract row mean from each row of a 2D array


arr=np.arange(5,17).reshape(3,4)
arr

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [37]:
r_mean=arr.mean(axis=1,keepdims=True)
new_arr=arr-r_mean
new_arr

array([[-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5],
       [-1.5, -0.5,  0.5,  1.5]])

In [39]:
# Given a 4×4 array, swap the first half rows with the second half rows

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [42]:
arr = np.roll(arr,2,axis=0)
arr

array([[11, 17, 22],
       [29, 19, 18],
       [17, 38, 19]], dtype=int32)

In [41]:
# Given a 1D array of random numbers, find the indices of the 5 largest values 
# (no sorting/ check argsort() instead)

arr=np.random.randint(10,42,9).reshape(3,3)
arr    

array([[17, 38, 19],
       [11, 17, 22],
       [29, 19, 18]], dtype=int32)

In [43]:
idx = np.argsort(arr, axis=None)
sorted_arr = arr.flatten()[idx]

n = 5
res = sorted_arr[-n:]
res

array([19, 19, 22, 29, 38], dtype=int32)

In [45]:
# From a 2D NumPy array, extract only the unique rows (no duplicates hint: check unique method)

arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3],
    [7, 8, 9],
    [4, 5, 6]
])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

In [46]:
unique_rows = np.unique(arr, axis=0)
unique_rows

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])