In [55]:
import numpy as np

In [56]:
arr=np.array([1,2,3,4,5,6,7])
arr

array([1, 2, 3, 4, 5, 6, 7])

In [57]:
arr.astype(float)

array([1., 2., 3., 4., 5., 6., 7.])

In [58]:
type(arr)

numpy.ndarray

In [59]:
arr.shape

(7,)

In [60]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
arr.ndim

1

In [62]:
arr.dtype

dtype('int64')

In [63]:
arr=arr.reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [64]:
arr.shape

(2, 5)

In [65]:
zeros=np.zeros([3,3])
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [66]:
ones=np.ones([3,3])
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [67]:
arr_b=np.full(9,True).reshape(3,3)
arr_b

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [68]:
arr_r=np.random.random([3,3])
arr_r

array([[0.84937072, 0.86522152, 0.59937263],
       [0.66235463, 0.05791323, 0.34131673],
       [0.03793219, 0.62234496, 0.94573168]])

In [69]:
arr_rd=np.random.randint(5,15,12) #start,end,total values
arr_rd

array([ 7, 13,  7,  8, 12, 14,  9,  7, 14, 11, 13, 11], dtype=int32)

In [70]:
arr_rd=np.random.randint(5,15,12).reshape(3,4)
arr_rd

array([[ 5, 13, 14,  6],
       [11,  7, 11,  9],
       [11, 14,  6, 13]], dtype=int32)

In [71]:
arr_l=np.linspace(2,20,10) #start end no.req
arr_l

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [72]:
arr_l=np.linspace(2,20,10) #start end no.req
arr_l

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [73]:
empty_a=np.empty([2,3]) #provide already available array
empty_a

array([[ 3. ,  6.4,  9.8],
       [13.2, 16.6, 20. ]])

In [74]:
id_a=np.identity(3)
id_a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [75]:
arr_rd.astype(float)

array([[ 5., 13., 14.,  6.],
       [11.,  7., 11.,  9.],
       [11., 14.,  6., 13.]])

In [76]:
empty_a=np.empty([3,4]) 
empty_a

array([[ 5., 13., 14.,  6.],
       [11.,  7., 11.,  9.],
       [11., 14.,  6., 13.]])

In [77]:
arr_rd

array([[ 5, 13, 14,  6],
       [11,  7, 11,  9],
       [11, 14,  6, 13]], dtype=int32)